package com.fatiharge.mapper;

import com.fatiharge.client.rest.openCurrencyApiClient.dto.fetchCurrenciesResponse.ApiCurrenciesResponse;
import com.fatiharge.dto.historicalPricesResponse.HistoricalPricesData;
import com.fatiharge.entity.HistoricalCurrencyPrice;
import org.mapstruct.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

@Mapper(componentModel = "cdi")
public interface HistoricalCurrencyMapper {
    HistoricalPricesData hcDataFromHistoricalCurrencyPrice(HistoricalCurrencyPrice data);

    @Named("stringToLocalDate")
    default LocalDate mapStringToLocalDate(String date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return LocalDate.parse(date, formatter);
    }

    @AfterMapping
    default void setBaseCurrency(
            @MappingTarget
            HistoricalCurrencyPrice target,
            String baseCurrency
    ) {
        target.baseCurrency = baseCurrency;
    }

    @Mapping(target = "ADA", source = "apiCurrenciesData.ADA")
    @Mapping(target = "AED", source = "apiCurrenciesData.AED")
    @Mapping(target = "AFN", source = "apiCurrenciesData.AFN")
    @Mapping(target = "ALL", source = "apiCurrenciesData.ALL")
    @Mapping(target = "AMD", source = "apiCurrenciesData.AMD")
    @Mapping(target = "ANG", source = "apiCurrenciesData.ANG")
    @Mapping(target = "AOA", source = "apiCurrenciesData.AOA")
    @Mapping(target = "ARB", source = "apiCurrenciesData.ARB")
    @Mapping(target = "ARS", source = "apiCurrenciesData.ARS")
    @Mapping(target = "AUD", source = "apiCurrenciesData.AUD")
    @Mapping(target = "AVAX", source = "apiCurrenciesData.AVAX")
    @Mapping(target = "AWG", source = "apiCurrenciesData.AWG")
    @Mapping(target = "AZN", source = "apiCurrenciesData.AZN")
    @Mapping(target = "BAM", source = "apiCurrenciesData.BAM")
    @Mapping(target = "BBD", source = "apiCurrenciesData.BBD")
    @Mapping(target = "BDT", source = "apiCurrenciesData.BDT")
    @Mapping(target = "BGN", source = "apiCurrenciesData.BGN")
    @Mapping(target = "BHD", source = "apiCurrenciesData.BHD")
    @Mapping(target = "BIF", source = "apiCurrenciesData.BIF")
    @Mapping(target = "BMD", source = "apiCurrenciesData.BMD")
    @Mapping(target = "BNB", source = "apiCurrenciesData.BNB")
    @Mapping(target = "BND", source = "apiCurrenciesData.BND")
    @Mapping(target = "BOB", source = "apiCurrenciesData.BOB")
    @Mapping(target = "BRL", source = "apiCurrenciesData.BRL")
    @Mapping(target = "BSD", source = "apiCurrenciesData.BSD")
    @Mapping(target = "BTC", source = "apiCurrenciesData.BTC")
    @Mapping(target = "BTN", source = "apiCurrenciesData.BTN")
    @Mapping(target = "BWP", source = "apiCurrenciesData.BWP")
    @Mapping(target = "BYN", source = "apiCurrenciesData.BYN")
    @Mapping(target = "BYR", source = "apiCurrenciesData.BYR")
    @Mapping(target = "BZD", source = "apiCurrenciesData.BZD")
    @Mapping(target = "CAD", source = "apiCurrenciesData.CAD")
    @Mapping(target = "CDF", source = "apiCurrenciesData.CDF")
    @Mapping(target = "CHF", source = "apiCurrenciesData.CHF")
    @Mapping(target = "CLP", source = "apiCurrenciesData.CLP")
    @Mapping(target = "CNY", source = "apiCurrenciesData.CNY")
    @Mapping(target = "COP", source = "apiCurrenciesData.COP")
    @Mapping(target = "CRC", source = "apiCurrenciesData.CRC")
    @Mapping(target = "CUC", source = "apiCurrenciesData.CUC")
    @Mapping(target = "CUP", source = "apiCurrenciesData.CUP")
    @Mapping(target = "CVE", source = "apiCurrenciesData.CVE")
    @Mapping(target = "CZK", source = "apiCurrenciesData.CZK")
    @Mapping(target = "DAI", source = "apiCurrenciesData.DAI")
    @Mapping(target = "DJF", source = "apiCurrenciesData.DJF")
    @Mapping(target = "DKK", source = "apiCurrenciesData.DKK")
    @Mapping(target = "DOP", source = "apiCurrenciesData.DOP")
    @Mapping(target = "DOT", source = "apiCurrenciesData.DOT")
    @Mapping(target = "DZD", source = "apiCurrenciesData.DZD")
    @Mapping(target = "EGP", source = "apiCurrenciesData.EGP")
    @Mapping(target = "ERN", source = "apiCurrenciesData.ERN")
    @Mapping(target = "ETB", source = "apiCurrenciesData.ETB")
    @Mapping(target = "ETH", source = "apiCurrenciesData.ETH")
    @Mapping(target = "EUR", source = "apiCurrenciesData.EUR")
    @Mapping(target = "FJD", source = "apiCurrenciesData.FJD")
    @Mapping(target = "FKP", source = "apiCurrenciesData.FKP")
    @Mapping(target = "GBP", source = "apiCurrenciesData.GBP")
    @Mapping(target = "GEL", source = "apiCurrenciesData.GEL")
    @Mapping(target = "GGP", source = "apiCurrenciesData.GGP")
    @Mapping(target = "GHS", source = "apiCurrenciesData.GHS")
    @Mapping(target = "GIP", source = "apiCurrenciesData.GIP")
    @Mapping(target = "GMD", source = "apiCurrenciesData.GMD")
    @Mapping(target = "GNF", source = "apiCurrenciesData.GNF")
    @Mapping(target = "GTQ", source = "apiCurrenciesData.GTQ")
    @Mapping(target = "GYD", source = "apiCurrenciesData.GYD")
    @Mapping(target = "HKD", source = "apiCurrenciesData.HKD")
    @Mapping(target = "HNL", source = "apiCurrenciesData.HNL")
    @Mapping(target = "HRK", source = "apiCurrenciesData.HRK")
    @Mapping(target = "HTG", source = "apiCurrenciesData.HTG")
    @Mapping(target = "HUF", source = "apiCurrenciesData.HUF")
    @Mapping(target = "IDR", source = "apiCurrenciesData.IDR")
    @Mapping(target = "ILS", source = "apiCurrenciesData.ILS")
    @Mapping(target = "IMP", source = "apiCurrenciesData.IMP")
    @Mapping(target = "INR", source = "apiCurrenciesData.INR")
    @Mapping(target = "IQD", source = "apiCurrenciesData.IQD")
    @Mapping(target = "IRR", source = "apiCurrenciesData.IRR")
    @Mapping(target = "ISK", source = "apiCurrenciesData.ISK")
    @Mapping(target = "JEP", source = "apiCurrenciesData.JEP")
    @Mapping(target = "JMD", source = "apiCurrenciesData.JMD")
    @Mapping(target = "JOD", source = "apiCurrenciesData.JOD")
    @Mapping(target = "JPY", source = "apiCurrenciesData.JPY")
    @Mapping(target = "KES", source = "apiCurrenciesData.KES")
    @Mapping(target = "KGS", source = "apiCurrenciesData.KGS")
    @Mapping(target = "KHR", source = "apiCurrenciesData.KHR")
    @Mapping(target = "KMF", source = "apiCurrenciesData.KMF")
    @Mapping(target = "KPW", source = "apiCurrenciesData.KPW")
    @Mapping(target = "KRW", source = "apiCurrenciesData.KRW")
    @Mapping(target = "KWD", source = "apiCurrenciesData.KWD")
    @Mapping(target = "KYD", source = "apiCurrenciesData.KYD")
    @Mapping(target = "KZT", source = "apiCurrenciesData.KZT")
    @Mapping(target = "LAK", source = "apiCurrenciesData.LAK")
    @Mapping(target = "LBP", source = "apiCurrenciesData.LBP")
    @Mapping(target = "LKR", source = "apiCurrenciesData.LKR")
    @Mapping(target = "LRD", source = "apiCurrenciesData.LRD")
    @Mapping(target = "LSL", source = "apiCurrenciesData.LSL")
    @Mapping(target = "LTC", source = "apiCurrenciesData.LTC")
    @Mapping(target = "LTL", source = "apiCurrenciesData.LTL")
    @Mapping(target = "LVL", source = "apiCurrenciesData.LVL")
    @Mapping(target = "LYD", source = "apiCurrenciesData.LYD")
    @Mapping(target = "MAD", source = "apiCurrenciesData.MAD")
    @Mapping(target = "MATIC", source = "apiCurrenciesData.MATIC")
    @Mapping(target = "MDL", source = "apiCurrenciesData.MDL")
    @Mapping(target = "MGA", source = "apiCurrenciesData.MGA")
    @Mapping(target = "MKD", source = "apiCurrenciesData.MKD")
    @Mapping(target = "MMK", source = "apiCurrenciesData.MMK")
    @Mapping(target = "MNT", source = "apiCurrenciesData.MNT")
    @Mapping(target = "MOP", source = "apiCurrenciesData.MOP")
    @Mapping(target = "MRO", source = "apiCurrenciesData.MRO")
    @Mapping(target = "MRU", source = "apiCurrenciesData.MRU")
    @Mapping(target = "MUR", source = "apiCurrenciesData.MUR")
    @Mapping(target = "MVR", source = "apiCurrenciesData.MVR")
    @Mapping(target = "MWK", source = "apiCurrenciesData.MWK")
    @Mapping(target = "MXN", source = "apiCurrenciesData.MXN")
    @Mapping(target = "MYR", source = "apiCurrenciesData.MYR")
    @Mapping(target = "MZN", source = "apiCurrenciesData.MZN")
    @Mapping(target = "NAD", source = "apiCurrenciesData.NAD")
    @Mapping(target = "NGN", source = "apiCurrenciesData.NGN")
    @Mapping(target = "NIO", source = "apiCurrenciesData.NIO")
    @Mapping(target = "NOK", source = "apiCurrenciesData.NOK")
    @Mapping(target = "NPR", source = "apiCurrenciesData.NPR")
    @Mapping(target = "NZD", source = "apiCurrenciesData.NZD")
    @Mapping(target = "OMR", source = "apiCurrenciesData.OMR")
    @Mapping(target = "OP", source = "apiCurrenciesData.OP")
    @Mapping(target = "PAB", source = "apiCurrenciesData.PAB")
    @Mapping(target = "PEN", source = "apiCurrenciesData.PEN")
    @Mapping(target = "PGK", source = "apiCurrenciesData.PGK")
    @Mapping(target = "PHP", source = "apiCurrenciesData.PHP")
    @Mapping(target = "PKR", source = "apiCurrenciesData.PKR")
    @Mapping(target = "PLN", source = "apiCurrenciesData.PLN")
    @Mapping(target = "PYG", source = "apiCurrenciesData.PYG")
    @Mapping(target = "QAR", source = "apiCurrenciesData.QAR")
    @Mapping(target = "RON", source = "apiCurrenciesData.RON")
    @Mapping(target = "RSD", source = "apiCurrenciesData.RSD")
    @Mapping(target = "RUB", source = "apiCurrenciesData.RUB")
    @Mapping(target = "RWF", source = "apiCurrenciesData.RWF")
    @Mapping(target = "SAR", source = "apiCurrenciesData.SAR")
    @Mapping(target = "SBD", source = "apiCurrenciesData.SBD")
    @Mapping(target = "SCR", source = "apiCurrenciesData.SCR")
    @Mapping(target = "SDG", source = "apiCurrenciesData.SDG")
    @Mapping(target = "SEK", source = "apiCurrenciesData.SEK")
    @Mapping(target = "SGD", source = "apiCurrenciesData.SGD")
    @Mapping(target = "SHP", source = "apiCurrenciesData.SHP")
    @Mapping(target = "SLL", source = "apiCurrenciesData.SLL")
    @Mapping(target = "SOL", source = "apiCurrenciesData.SOL")
    @Mapping(target = "SOS", source = "apiCurrenciesData.SOS")
    @Mapping(target = "SRD", source = "apiCurrenciesData.SRD")
    @Mapping(target = "STD", source = "apiCurrenciesData.STD")
    @Mapping(target = "STN", source = "apiCurrenciesData.STN")
    @Mapping(target = "SVC", source = "apiCurrenciesData.SVC")
    @Mapping(target = "SYP", source = "apiCurrenciesData.SYP")
    @Mapping(target = "SZL", source = "apiCurrenciesData.SZL")
    @Mapping(target = "THB", source = "apiCurrenciesData.THB")
    @Mapping(target = "TJS", source = "apiCurrenciesData.TJS")
    @Mapping(target = "TMT", source = "apiCurrenciesData.TMT")
    @Mapping(target = "TND", source = "apiCurrenciesData.TND")
    @Mapping(target = "TOP", source = "apiCurrenciesData.TOP")
    @Mapping(target = "TRY", source = "apiCurrenciesData.TRY")
    @Mapping(target = "TTD", source = "apiCurrenciesData.TTD")
    @Mapping(target = "TWD", source = "apiCurrenciesData.TWD")
    @Mapping(target = "TZS", source = "apiCurrenciesData.TZS")
    @Mapping(target = "UAH", source = "apiCurrenciesData.UAH")
    @Mapping(target = "UGX", source = "apiCurrenciesData.UGX")
    @Mapping(target = "USD", source = "apiCurrenciesData.USD")
    @Mapping(target = "USDC", source = "apiCurrenciesData.USDC")
    @Mapping(target = "USDT", source = "apiCurrenciesData.USDT")
    @Mapping(target = "UYU", source = "apiCurrenciesData.UYU")
    @Mapping(target = "UZS", source = "apiCurrenciesData.UZS")
    @Mapping(target = "VEF", source = "apiCurrenciesData.VEF")
    @Mapping(target = "VES", source = "apiCurrenciesData.VES")
    @Mapping(target = "VND", source = "apiCurrenciesData.VND")
    @Mapping(target = "VUV", source = "apiCurrenciesData.VUV")
    @Mapping(target = "WST", source = "apiCurrenciesData.WST")
    @Mapping(target = "XAF", source = "apiCurrenciesData.XAF")
    @Mapping(target = "XAG", source = "apiCurrenciesData.XAG")
    @Mapping(target = "XAU", source = "apiCurrenciesData.XAU")
    @Mapping(target = "XCD", source = "apiCurrenciesData.XCD")
    @Mapping(target = "XDR", source = "apiCurrenciesData.XDR")
    @Mapping(target = "XOF", source = "apiCurrenciesData.XOF")
    @Mapping(target = "XPD", source = "apiCurrenciesData.XPD")
    @Mapping(target = "XPF", source = "apiCurrenciesData.XPF")
    @Mapping(target = "XPT", source = "apiCurrenciesData.XPT")
    @Mapping(target = "XRP", source = "apiCurrenciesData.XRP")
    @Mapping(target = "YER", source = "apiCurrenciesData.YER")
    @Mapping(target = "ZAR", source = "apiCurrenciesData.ZAR")
    @Mapping(target = "ZMK", source = "apiCurrenciesData.ZMK")
    @Mapping(target = "ZMW", source = "apiCurrenciesData.ZMW")
    @Mapping(target = "ZWL", source = "apiCurrenciesData.ZWL")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "baseCurrency", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "date", source = "date", qualifiedByName = "stringToLocalDate")
    HistoricalCurrencyPrice historicalCurrencyPriceFromApiResponse(
            ApiCurrenciesResponse ApiCurrenciesResponse
    );


}


